#!/bin/bash
# 修复balance_strategy_display.html的CSS样式

FILE="balance_strategy_display.html"

# 备份文件
cp "$FILE" "${FILE}.backup.$(date +%Y%m%d_%H%M%S)"

# 在</style>标签前添加CSS样式
sed -i '/<\/style>/i\        /* 新添加的样式 - 计算公式卡片 */' "$FILE"
sed -i '/<\/style>/i\        .formula-section {' "$FILE"
sed -i '/<\/style>/i\            padding: 10px 0;' "$FILE"
sed -i '/<\/style>/i\        }' "$FILE"
sed -i '/<\/style>/i\        ' "$FILE"
sed -i '/<\/style>/i\        .formula-section h4 {' "$FILE"
sed -i '/<\/style>/i\            color: #22d3ee;' "$FILE"
sed -i '/<\/style>/i\            margin-bottom: 15px;' "$FILE"
sed -i '/<\/style>/i\            font-size: 1.2rem;' "$FILE"
sed -i '/<\/style>/i\        }' "$FILE"
sed -i '/<\/style>/i\        ' "$FILE"
sed -i '/<\/style>/i\        .formula-box {' "$FILE"
sed -i '/<\/style>/i\            background: rgba(34, 211, 238, 0.1);' "$FILE"
sed -i '/<\/style>/i\            border-left: 4px solid #22d3ee;' "$FILE"
sed -i '/<\/style>/i\            padding: 15px;' "$FILE"
sed -i '/<\/style>/i\            margin: 15px 0;' "$FILE"
sed -i '/<\/style>/i\            font-family: "Courier New", monospace;' "$FILE"
sed -i '/<\/style>/i\            font-size: 1.1rem;' "$FILE"
sed -i '/<\/style>/i\            color: #e2e8f0;' "$FILE"
sed -i '/<\/style>/i\            border-radius: 0 8px 8px 0;' "$FILE"
sed -i '/<\/style>/i\        }' "$FILE"
sed -i '/<\/style>/i\        ' "$FILE"
sed -i '/<\/style>/i\        .formula-explanation {' "$FILE"
sed -i '/<\/style>/i\            margin: 20px 0;' "$FILE"
sed -i '/<\/style>/i\        }' "$FILE"
sed -i '/<\/style>/i\        ' "$FILE"
sed -i '/<\/style>/i\        .explanation-item {' "$FILE"
sed -i '/<\/style>/i\            margin-bottom: 12px;' "$FILE"
sed -i '/<\/style>/i\            padding: 10px;' "$FILE"
sed -i '/<\/style>/i\            background: rgba(30, 41, 59, 0.7);' "$FILE"
sed -i '/<\/style>/i\            border-radius: 8px;' "$FILE"
sed -i '/<\/style>/i\            border-left: 3px solid #f97316;' "$FILE"
sed -i '/<\/style>/i\        }' "$FILE"
sed -i '/<\/style>/i\        ' "$FILE"
sed -i '/<\/style>/i\        .formula-detail {' "$FILE"
sed -i '/<\/style>/i\            display: block;' "$FILE"
sed -i '/<\/style>/i\            font-size: 0.9rem;' "$FILE"
sed -i '/<\/style>/i\            color: #94a3b8;' "$FILE"
sed -i '/<\/style>/i\            margin-top: 5px;' "$FILE"
sed -i '/<\/style>/i\            padding-left: 10px;' "$FILE"
sed -i '/<\/style>/i\        }' "$FILE"
sed -i '/<\/style>/i\        ' "$FILE"
sed -i '/<\/style>/i\        .example-table table {' "$FILE"
sed -i '/<\/style>/i\            width: 100%;' "$FILE"
sed -i '/<\/style>/i\            border-collapse: collapse;' "$FILE"
sed -i '/<\/style>/i\            margin: 15px 0;' "$FILE"
sed -i '/<\/style>/i\        }' "$FILE"
sed -i '/<\/style>/i\        ' "$FILE"
sed -i '/<\/style>/i\        .example-table th {' "$FILE"
sed -i '/<\/style>/i\            background: rgba(34, 211, 238, 0.2);' "$FILE"
sed -i '/<\/style>/i\            color: #22d3ee;' "$FILE"
sed -i '/<\/style>/i\            padding: 10px;' "$FILE"
sed -i '/<\/style>/i\            text-align: left;' "$FILE"
sed -i '/<\/style>/i\            border-bottom: 2px solid #22d3ee;' "$FILE"
sed -i '/<\/style>/i\        }' "$FILE"
sed -i '/<\/style>/i\        ' "$FILE"
sed -i '/<\/style>/i\        .example-table td {' "$FILE"
sed -i '/<\/style>/i\            padding: 10px;' "$FILE"
sed -i '/<\/style>/i\            border-bottom: 1px solid rgba(100, 116, 139, 0.3);' "$FILE"
sed -i '/<\/style>/i\        }' "$FILE"
sed -i '/<\/style>/i\        ' "$FILE"
sed -i '/<\/style>/i\        .example-table tr:hover {' "$FILE"
sed -i '/<\/style>/i\            background: rgba(34, 211, 238, 0.05);' "$FILE"
sed -i '/<\/style>/i\        }' "$FILE"

echo "✅ CSS样式修复完成！"
echo "页面现在应该正常显示新卡片。"